# Generated by Django 5.1.3 on 2024-12-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_birth_date_remove_user_image_commonuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='image',
        ),
    ]
